// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrKDjGwBpktllHSxu5EMXLmVO1BpM1v74',
    appId: '1:83866223967:web:c7961ef039fc27d8d3e2ea',
    messagingSenderId: '83866223967',
    projectId: 'business-whatsapp-flutter',
    authDomain: 'business-whatsapp-flutter.firebaseapp.com',
    storageBucket: 'business-whatsapp-flutter.appspot.com',
    measurementId: 'G-XCQPTFN3D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB_nRpzSyooU4bYdpJYoi5gn61KntFGWA',
    appId: '1:83866223967:android:b3a01955bfb664add3e2ea',
    messagingSenderId: '83866223967',
    projectId: 'business-whatsapp-flutter',
    storageBucket: 'business-whatsapp-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVnJ_3NRwUYPMx-OSH1h8HDlVJdWcB4CI',
    appId: '1:83866223967:ios:787935d11116e470d3e2ea',
    messagingSenderId: '83866223967',
    projectId: 'business-whatsapp-flutter',
    storageBucket: 'business-whatsapp-flutter.appspot.com',
    iosBundleId: 'com.example.chatMessageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVnJ_3NRwUYPMx-OSH1h8HDlVJdWcB4CI',
    appId: '1:83866223967:ios:787935d11116e470d3e2ea',
    messagingSenderId: '83866223967',
    projectId: 'business-whatsapp-flutter',
    storageBucket: 'business-whatsapp-flutter.appspot.com',
    iosBundleId: 'com.example.chatMessageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrKDjGwBpktllHSxu5EMXLmVO1BpM1v74',
    appId: '1:83866223967:web:e22f28c4f49292b4d3e2ea',
    messagingSenderId: '83866223967',
    projectId: 'business-whatsapp-flutter',
    authDomain: 'business-whatsapp-flutter.firebaseapp.com',
    storageBucket: 'business-whatsapp-flutter.appspot.com',
    measurementId: 'G-QQKNPWC2ZM',
  );
}
